apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-html
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>{{ .Chart.Name }}</title></head>
    <body>
      <h1>{{ .Values.html.message }}</h1>
    </body>
    </html>
