apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Hello K8s 2</title></head>
    <body>
      <h1>Hello from Kubernetes – exercise 2 🌀</h1>
    </body>
    </html>
